### ISSUE TITLE
AttributeError: module 'transformers_modules.123.tokenization_qwen' has no attribute 'QWenTokenizer'

### ISSUE THREAD

**Issue by vivixx1** [modelscope/swift#590]
AttributeError: module 'transformers_modules.123.tokenization_qwen' has no attribute 'QWenTokenizer'
在8张A800机器上lora微调qwen-72b-chat-int8时报错，下面是我的脚本

export NCCL_P2P_DISABLE=1
export NCCL_IB_DISABLE=1
export NCCL_DEBUG=info
export NCCL_SOCKET_IFNAME=eth0
nproc_per_node=8

PYTHONPATH=../../.. \
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 \
torchrun \
    --nproc_per_node=$nproc_per_node \
    --master_port 29500 \
    /swift/examples/pytorch/llm/llm_sft.py \
    --model_id_or_path /ai/123/123/ --model_type qwen-72b-chat-int8 \
    --model_revision master \
    --sft_type lora \
    --tuner_backend swift \
    --template_type AUTO \
    --dtype AUTO \
    --output_dir /ai/outfile/ \
    --ddp_backend nccl \
    --custom_train_dataset_path /ai/123/训练集4.1_prompt.jsonl \
    --train_dataset_sample -1 \
    --num_train_epochs 3 \
    --max_length 2048 \
    --truncation_strategy delete \
    --check_dataset_strategy warning \
    --lora_rank 8 \
    --lora_alpha 32 \
    --lora_dropout_p 0.05 \
    --lora_target_modules DEFAULT \
    --gradient_checkpointing true \
    --batch_size 1 \
    --weight_decay 0.01 \
    --learning_rate 1e-4 \
    --gradient_accumulation_steps $(expr 16 / $nproc_per_node) \
    --max_grad_norm 0.5 \
    --warmup_ratio 0.03 \
    --eval_steps 50 \
    --save_total_limit 2 \
    --logging_steps 1 \
    --deepspeed default-zero2 \
    --save_only_model true \

下面是我的环境
absl-py                       2.1.0
accelerate                    0.28.0
addict                        2.4.0
aiofiles                      23.2.1
aiohttp                       3.9.3
aiosignal                     1.3.1
aliyun-python-sdk-core        2.15.0
aliyun-python-sdk-kms         2.16.2
altair                        5.2.0
annotated-types               0.6.0
anyio                         4.3.0
argon2-cffi                   23.1.0
argon2-cffi-bindings          21.2.0
arrow                         1.3.0
asttokens                     2.4.1
async-lru                     2.0.4
async-timeout                 4.0.3
attrs                         23.2.0
auto_gptq                     0.7.1
Babel                         2.14.0
backcall                      0.2.0
beautifulsoup4                4.12.3
bleach                        6.1.0
cachetools                    5.3.3
certifi                       2024.2.2
cffi                          1.16.0
charset-normalizer            3.3.2
click                         8.1.7
colorama                      0.4.6
coloredlogs                   15.0.1
comm                          0.2.2
contourpy                     1.1.1
cpm-kernels                   1.0.11
crcmod                        1.7
cryptography                  42.0.5
cycler                        0.12.1
dacite                        1.8.1
datasets                      2.18.0
debugpy                       1.8.1
decorator                     5.1.1
deepspeed                     0.14.0
defusedxml                    0.7.1
dill                          0.3.8
docstring_parser              0.16
einops                        0.7.0
exceptiongroup                1.2.0
executing                     2.0.1
fastapi                       0.110.0
fastjsonschema                2.19.1
ffmpy                         0.3.2
filelock                      3.13.1
flash-attn                    2.5.5
fonttools                     4.50.0
fqdn                          1.5.1
frozenlist                    1.4.1
fsspec                        2024.2.0
gast                          0.5.4
gekko                         1.0.7
google-auth                   2.28.2
google-auth-oauthlib          1.0.0
gradio                        4.22.0
gradio_client                 0.13.0
grpcio                        1.62.1
h11                           0.14.0
hjson                         3.1.0
httpcore                      1.0.4
httpx                         0.27.0
huggingface-hub               0.21.4
humanfriendly                 10.0
idna                          3.6
importlib_metadata            7.0.2
importlib_resources           6.3.2
ipykernel                     6.29.3
ipython                       8.12.3
isoduration                   20.11.0
jedi                          0.19.1
jieba                         0.42.1
Jinja2                        3.1.3
jmespath                      0.10.0
joblib                        1.3.2
json5                         0.9.24
jsonpointer                   2.4
jsonschema                    4.21.1
jsonschema-specifications     2023.12.1
jupyter_client                8.6.1
jupyter_core                  5.7.2
jupyter-events                0.10.0
jupyter-lsp                   2.2.4
jupyter_server                2.13.0
jupyter_server_terminals      0.5.3
jupyterlab                    4.1.5
jupyterlab_pygments           0.3.0
jupyterlab_server             2.25.4
kiwisolver                    1.4.5
Markdown                      3.6
markdown-it-py                3.0.0
MarkupSafe                    2.1.5
matplotlib                    3.7.5
matplotlib-inline             0.1.6
mdurl                         0.1.2
mistune                       3.0.2
modelscope                    1.13.1
mpmath                        1.3.0
ms-swift                      1.8.0.dev0     /swift
multidict                     6.0.5
multiprocess                  0.70.16
nbclient                      0.10.0
nbconvert                     7.16.2
nbformat                      5.10.3
nest-asyncio                  1.6.0
networkx                      3.1
ninja                         1.11.1.1
nltk                          3.8.1
notebook                      7.1.2
notebook_shim                 0.2.4
numpy                         1.24.4
nvidia-cublas-cu12            12.1.3.1
nvidia-cuda-cupti-cu12        12.1.105
nvidia-cuda-nvrtc-cu12        12.1.105
nvidia-cuda-runtime-cu12      12.1.105
nvidia-cudnn-cu12             8.9.2.26
nvidia-cufft-cu12             11.0.2.54
nvidia-curand-cu12            10.3.2.106
nvidia-cusolver-cu12          11.4.5.107
nvidia-cusparse-cu12          12.1.0.106
nvidia-nccl-cu12              2.19.3
nvidia-nvjitlink-cu12         12.4.99
nvidia-nvtx-cu12              12.1.105
oauthlib                      3.2.2
optimum                       1.17.1
orjson                        3.9.15
oss2                          2.18.4
overrides                     7.7.0
packaging                     24.0
pandas                        2.0.3
pandocfilters                 1.5.1
parso                         0.8.3
peft                          0.9.0
pexpect                       4.9.0
pickleshare                   0.7.5
pillow                        10.2.0
pip                           24.0
pkgutil_resolve_name          1.3.10
platformdirs                  4.2.0
prometheus_client             0.20.0
prompt-toolkit                3.0.43
protobuf                      5.26.0
psutil                        5.9.8
ptyprocess                    0.7.0
pure-eval                     0.2.2
py-cpuinfo                    9.0.0
pyarrow                       15.0.2
pyarrow-hotfix                0.6
pyasn1                        0.5.1
pyasn1-modules                0.3.0
pycparser                     2.21
pycryptodome                  3.20.0
pydantic                      2.6.4
pydantic_core                 2.16.3
pydub                         0.25.1
Pygments                      2.17.2
pynvml                        11.5.0
pyparsing                     3.1.2
python-dateutil               2.9.0.post0
python-json-logger            2.0.7
python-multipart              0.0.9
pytz                          2024.1
PyYAML                        6.0.1
pyzmq                         25.1.2
referencing                   0.34.0
regex                         2023.12.25
requests                      2.31.0
requests-oauthlib             1.4.0
rfc3339-validator             0.1.4
rfc3986-validator             0.1.1
rich                          13.7.1
rouge                         1.0.1
rpds-py                       0.18.0
rsa                           4.9
ruff                          0.3.3
safetensors                   0.4.2
scipy                         1.10.1
semantic-version              2.10.0
Send2Trash                    1.8.2
sentencepiece                 0.2.0
setuptools                    45.2.0
shellingham                   1.5.4
shtab                         1.7.1
simplejson                    3.19.2
six                           1.16.0
sniffio                       1.3.1
sortedcontainers              2.4.0
soupsieve                     2.5
stack-data                    0.6.3
starlette                     0.36.3
sympy                         1.12
tensorboard                   2.14.0
tensorboard-data-server       0.7.2
terminado                     0.18.1
tiktoken                      0.6.0
tinycss2                      1.2.1
tokenizers                    0.15.2
tomli                         2.0.1
tomlkit                       0.12.0
toolz                         0.12.1
torch                         2.2.1
tornado                       6.4
tqdm                          4.66.2
traitlets                     5.14.2
transformers                  4.38.2
transformers-stream-generator 0.0.5
triton                        2.2.0
trl                           0.8.0
typer                         0.9.0
types-python-dateutil         2.9.0.20240316
typing_extensions             4.10.0
tyro                          0.7.3
tzdata                        2024.1
uri-template                  1.3.0
urllib3                       2.2.1
uvicorn                       0.28.1
wcwidth                       0.2.13
webcolors                     1.13
webencodings                  0.5.1
websocket-client              1.7.0
websockets                    11.0.3
Werkzeug                      3.0.1
wheel                         0.34.2
xxhash                        3.4.1
yapf                          0.40.2
yarl                          1.9.4
zipp                          3.18.1

**Comment by vivixx1** [comment]
在这之前碰到了nccl死锁问题和缺少fused_adam.so的问题，所以在脚本前面加了四个环境变量解决了nccl死锁问题，然后通过DS_BUILD_UTILS=1 DS_BUILD_FUSED_ADAM=1 pip install deepspeed -U命令解决了缺少fused_adam.so的问题

**Comment by vivixx1** [comment]
flash attention是在github手动下载的，flash_attn-2.5.5+cu122torch2.2cxx11abiFALSE-cp38-cp38-linux_x86_64，然后进入环境手动pip安装这个包

**Comment by vivixx1** [comment]
[rank0]:[E ProcessGroupNCCL.cpp:523] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=2, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=1800000) ran for 1800149 milliseconds before timing out.
[rank7]:[E ProcessGroupNCCL.cpp:523] [Rank 7] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=BROADCAST, NumelIn=1024, NumelOut=1024, Timeout(ms)=1800000) ran for 1800326 milliseconds before timing out.
[rank3]:[E ProcessGroupNCCL.cpp:523] [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=BROADCAST, NumelIn=1024, NumelOut=1024, Timeout(ms)=1800000) ran for 1800329 milliseconds before timing out.
[rank4]:[E ProcessGroupNCCL.cpp:523] [Rank 4] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=BROADCAST, NumelIn=1024, NumelOut=1024, Timeout(ms)=1800000) ran for 1800341 milliseconds before timing out.
[rank1]:[E ProcessGroupNCCL.cpp:523] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=2, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=1800000) ran for 1800304 milliseconds before timing out.
[rank6]:[E ProcessGroupNCCL.cpp:523] [Rank 6] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=BROADCAST, NumelIn=1024, NumelOut=1024, Timeout(ms)=1800000) ran for 1800375 milliseconds before timing out.
[rank2]:[E ProcessGroupNCCL.cpp:523] [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=BROADCAST, NumelIn=1024, NumelOut=1024, Timeout(ms)=1800000) ran for 1800376 milliseconds before timing out.
device_count: 8
这是死锁问题的log


ImportError: /root/.cache/torch_extensions/py38_cu121/fused_adam/fused_adam.so: cannot open shared object file: No such file or directory

这是fused_adam问题的log

**Comment by vivixx1** [comment]
我靠好像是flash attention版本问题。。。。我先试试

**Comment by vivixx1** [comment]
不对，应该不是，flash只有cu118和cu122，我的cuda版本上面是12.1，应该没问题

**Comment by vivixx1** [comment]
麻烦各位大佬和作者帮忙看看

**Comment by vivixx1** [comment]
奇怪，我再次运行的时候为什么又是fused_adam的问题了

**Comment by vivixx1** [comment]
Loading extension module fused_adam...
    model, self.optimizer, self.lr_scheduler = self.accelerator.prepare(
  File "/usr/local/lib/python3.8/dist-packages/accelerate/accelerator.py", line 1255, in prepare
Traceback (most recent call last):
  File "/swift/examples/pytorch/llm/llm_sft.py", line 7, in <module>
    output = sft_main()
  File "/swift/swift/utils/run_utils.py", line 31, in x_main
    result = self._prepare_deepspeed(*args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/accelerator.py", line 1640, in _prepare_deepspeed
    result = llm_x(args, **kwargs)
  File "/swift/swift/llm/sft.py", line 236, in llm_sft
    trainer.train(training_args.resume_from_checkpoint)
  File "/swift/swift/trainers/trainers.py", line 50, in train
    res = super().train(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 1624, in train
    engine, optimizer, _, lr_scheduler = deepspeed.initialize(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/__init__.py", line 176, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/runtime/engine.py", line 307, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/runtime/engine.py", line 1230, in _configure_optimizer
    return inner_training_loop(
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 1779, in _inner_training_loop
    basic_optimizer = self._configure_basic_optimizer(model_parameters)
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/runtime/engine.py", line 1307, in _configure_basic_optimizer
    model, self.optimizer, self.lr_scheduler = self.accelerator.prepare(
  File "/usr/local/lib/python3.8/dist-packages/accelerate/accelerator.py", line 1255, in prepare
    optimizer = FusedAdam(
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/ops/adam/fused_adam.py", line 94, in __init__
    fused_adam_cuda = FusedAdamBuilder().load()
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/ops/op_builder/builder.py", line 479, in load
    return self.jit_load(verbose)
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/ops/op_builder/builder.py", line 523, in jit_load
    result = self._prepare_deepspeed(*args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/accelerator.py", line 1640, in _prepare_deepspeed
    op_module = load(name=self.name,
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 1306, in load
    engine, optimizer, _, lr_scheduler = deepspeed.initialize(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/__init__.py", line 176, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/runtime/engine.py", line 307, in __init__
    return _jit_compile(
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 1710, in _jit_compile
    self._configure_optimizer(optimizer, model_parameters)
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/runtime/engine.py", line 1230, in _configure_optimizer
    basic_optimizer = self._configure_basic_optimizer(model_parameters)
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/runtime/engine.py", line 1307, in _configure_basic_optimizer
    _write_ninja_file_and_build_library(
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 1797, in _write_ninja_file_and_build_library
    optimizer = FusedAdam(
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/ops/adam/fused_adam.py", line 94, in __init__
    fused_adam_cuda = FusedAdamBuilder().load()
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/ops/op_builder/builder.py", line 479, in load
    get_compiler_abi_compatibility_and_version(compiler)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 359, in get_compiler_abi_compatibility_and_version
    return self.jit_load(verbose)
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/ops/op_builder/builder.py", line 523, in jit_load
    if not check_compiler_ok_for_platform(compiler):
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 312, in check_compiler_ok_for_platform
    which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
    op_module = load(name=self.name,  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output

  File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 1306, in load
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    return _jit_compile(
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 1736, in _jit_compile
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['which', 'c++']' returned non-zero exit status 1.
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 2132, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1166, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /root/.cache/torch_extensions/py38_cu121/fused_adam/fused_adam.so: cannot open shared object file: No such file or directory

**Comment by vivixx1** [comment]
[ERROR:swift] Authentication token does not exist, failed to access model unknown which may not exist or may be                 private. Please login first.
上面还报了一堆这个，不过我看别的issue说不需要管就没管了

**Comment by vivixx1** [comment]
export NCCL_P2P_DISABLE=1
export NCCL_IB_DISABLE=1
export NCCL_DEBUG=info
export NCCL_SOCKET_IFNAME=eth0
nproc_per_node=8

PYTHONPATH=../../.. \
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 \
torchrun \
    --nproc_per_node=$nproc_per_node \
    --master_port 29500 \
    /swift/examples/pytorch/llm/llm_sft.py \
    --model_type qwen-72b-chat-int8 --model_id_or_path /ai/123/123/ \
    --model_revision master \
    --sft_type lora \
    --tuner_backend swift \
    --template_type AUTO \
    --dtype AUTO \
    --output_dir /ai/outfile/ \
    --ddp_backend nccl \
    --custom_train_dataset_path /ai/123/训练集4.1_prompt.jsonl \
    --train_dataset_sample -1 \
    --num_train_epochs 3 \
    --max_length 2048 \
    --truncation_strategy delete \
    --check_dataset_strategy warning \
    --lora_rank 8 \
    --lora_alpha 32 \
    --lora_dropout_p 0.05 \
    --lora_target_modules DEFAULT \
    --gradient_checkpointing true \
    --batch_size 1 \
    --weight_decay 0.01 \
    --learning_rate 1e-4 \
    --gradient_accumulation_steps $(expr 16 / $nproc_per_node) \
    --max_grad_norm 0.5 \
    --warmup_ratio 0.03 \
    --eval_steps 50 \
    --save_total_limit 2 \
    --logging_steps 1 \
    --use_flash_attn true \
    --deepspeed default-zero2 \
    --save_only_model true \

**Comment by Jintao-Huang** [comment]
deepspeed现在和qlora并不兼容
建议直接微调 qwen-72b-chat, 并开启zero3

**Comment by vivixx1** [comment]
# 设置镜像
RUN pip config set global.index-url https://mirrors.aliyun.com/pypi/simple/

# Install ms-swift
RUN git clone https://github.com/modelscope/swift.git
RUN cd swift && pip install -e .[llm]

# Install deepspeed
RUN pip install deepspeed -U

# install auto-gptq
RUN pip install auto-gptq

这是我dockerfile的内容，flash attention是手动安装的

**Comment by vivixx1** [comment]
我通过ds_report查看到确实没有安装fused_adam.so，而且与系统是兼容的，我还发现nvcc版本找不到，似乎用上面dockerfile安装cuda的时候并没有安装nvcc，完全搜不到nvcc这个目录或者文件，我可能需要重新安装nvcc
[INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
fused_adam ............. [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_lion ............... [NO] ....... [OKAY]
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
evoformer_attn ......... [NO] ....... [NO]
fused_lamb ............. [NO] ....... [OKAY]
fused_lion ............. [NO] ....... [OKAY]
inference_core_ops ..... [NO] ....... [OKAY]
cutlass_ops ............ [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
ragged_device_ops ...... [NO] ....... [OKAY]
ragged_ops ............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.2
 [WARNING]  using untested triton version (2.2.0), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/usr/local/lib/python3.8/dist-packages/torch']
torch version .................... 2.2.1+cu121
deepspeed install path ........... ['/usr/local/lib/python3.8/dist-packages/deepspeed']
deepspeed info ................... 0.14.0, unknown, unknown
torch cuda version ............... 12.1
torch hip version ................ None
nvcc version .....................  [FAIL] cannot find CUDA_HOME via torch.utils.cpp_extension.CUDA_HOME=None 
deepspeed wheel compiled w. ...... torch 2.2, cuda 12.1
shared memory (/dev/shm) size .... 64.00 MB
  [WARNING] /dev/shm size might be too small, if running in docker increase to at least --shm-size='1gb' 
  [WARNING] see more details about NCCL requirements: https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/troubleshooting.html#sharing-data

**Comment by vivixx1** [comment]
不出意外这个nvcc是在cuda toolkit里面的，为啥没有直接装上啊。。。。

**Comment by Jintao-Huang** [comment]
shared memory (/dev/shm) size .... 64.00 MB
[WARNING] /dev/shm size might be too small, if running in docker increase to at least --shm-size='1gb'

**Comment by vivixx1** [comment]
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
deepspeed_not_implemented  [NO] ....... [OKAY]
deepspeed_ccl_comm ..... [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
fused_adam ............. [YES] ...... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/usr/local/lib/python3.8/dist-packages/torch']
torch version .................... 2.2.1+cu121
deepspeed install path ........... ['/usr/local/lib/python3.8/dist-packages/deepspeed']
deepspeed info ................... 0.14.1+0529eac6, 0529eac6, master
deepspeed wheel compiled w. ...... torch 2.2 
shared memory (/dev/shm) size .... 64.00 MB
  [WARNING] /dev/shm size might be too small, if running in docker increase to at least --shm-size='1gb' 

重新安装了一个12.1版本的cuda toolkit，然后有nvcc了，再按照下面的命令安装，就有fused_adam.so了
git clone https://github.com/microsoft/DeepSpeed.git
cd DeepSpeed
DS_BUILD_FUSED_ADAM=1 pip3 install .

**Comment by vivixx1** [comment]
解决了，确实是没有cuda toolkit的问题
![bf92894fcec74fdfc5cfd0316693138](https://github.com/modelscope/swift/assets/143391981/c7d5fffb-8e55-4627-ad2b-4f45979b1a9e)

**Comment by vivixx1** [comment]
大家可以参考我的方式去排查问题，以及安装对应的库

**Comment by stay-leave** [comment]
> ## JIT compiled ops requires ninja
> ninja .................. [OKAY]
> ## op name ................ installed .. compatible
> ## deepspeed_not_implemented [NO] ....... [OKAY]
> deepspeed_ccl_comm ..... [NO] ....... [OKAY]
> cpu_adam ............... [NO] ....... [OKAY]
> fused_adam ............. [YES] ...... [OKAY]
> DeepSpeed general environment info: torch install path ............... ['/usr/local/lib/python3.8/dist-packages/torch'] torch version .................... 2.2.1+cu121 deepspeed install path ........... ['/usr/local/lib/python3.8/dist-packages/deepspeed'] deepspeed info ................... 0.14.1+0529eac6, 0529eac6, master deepspeed wheel compiled w. ...... torch 2.2 shared memory (/dev/shm) size .... 64.00 MB [WARNING] /dev/shm size might be too small, if running in docker increase to at least --shm-size='1gb'
> 
> 重新安装了一个12.1版本的cuda toolkit，然后有nvcc了，再按照下面的命令安装，就有fused_adam.so了 git clone https://github.com/microsoft/DeepSpeed.git cd DeepSpeed DS_BUILD_FUSED_ADAM=1 pip3 install .

成功，感谢
