### ISSUE TITLE
无法将lora微调后的模型用于推理自己的测试集

### ISSUE THREAD

**Issue by vivixx1** [modelscope/swift#613]
# Experimental environment: 2 * A100
export NCCL_P2P_DISABLE=1
export NCCL_IB_DISABLE=1
export NCCL_DEBUG=info
export NCCL_SOCKET_IFNAME=eth0

PYTHONPATH=../../.. \
CUDA_VISIBLE_DEVICES=0,1 \
python /swift/examples/pytorch/llm/llm_infer.py \
    --ckpt_dir "/ai/outfile/qwen-72b-chat-int8/v8-20240325-144934/checkpoint-159/" \
    --model_type qwen-72b-chat-int8 --model_id_or_path /ai/123/123/ \
    --custom_val_dataset_path /ai/123/测试集4.1.jsonl \
    --val_dataset_sample -1 \
    --load_dataset_config true \
    --use_flash_attn true \
    --max_new_tokens 2048 \
    --temperature 0.1 \
    --top_p 0.7 \
    --repetition_penalty 1. \
    --do_sample true \
    --merge_lora false \

以上是我的iner.sh脚本

下面是我的测试集部分数据
{"query": "在$$\\triangle ACD$$和$$\\triangle BCE$$中, 点$$C$$在线段$$AB$$上，$$\\angle A = \\angle B = \\angle DCE$$，$$CE=CD$$．求证：$$\\triangle ACD \\cong \\triangle BEC$$. ", "response": " HYPOTHESES: \nPOINT A B C D E\nON_LINE C A B\nEQANGLE B A D E B A\nEQANGLE B A D E C D\nEQDISTANCE C E C D\nSHOW: CON_TRIANGLE A C D B E C "}
{"query": "在$$\\triangle ABC$$中，$$AB=AC$$，$$D$$为$$BC$$边上一点，在$$AD$$延长线上有一点$$E$$，连结$$EC$$，使得$$\\angle DCE=\\angle BAE$$，求证：$$\\triangle ABD \\sim \\triangle CED$$。", "response": "HYPOTHESES: \nPOINT A B C D E\nTRIANGLE A B C\nEQDISTANCE A B C A\nON_LINE D B C\nS_ANGLE A D E 180\nEQANGLE D A B E C B\nSHOW: SIM_TRIANGLE A B D C E DF"}

![image](https://github.com/modelscope/swift/assets/143391981/48444fca-a51e-4ce4-a99a-0fc215e30087)

RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

这是报错的日志
我想请问这是为什么。。。。

**Comment by vivixx1** [comment]
能不能自定义一个推理的py文件，我想按行读入我的测试集，并返回response保存到一个jsonl中，便于我之后进行评估效果

**Comment by zzisbeauty** [comment]
halo。我想请教一下呀~

说明文档中：https://github.com/modelscope/swift/blob/main/docs/source/LLM/LLM%E5%BE%AE%E8%B0%83%E6%96%87%E6%A1%A3.md#merge-lora

给的模型 merge lora 脚本是：

```
# 如果你需要量化, 可以指定`--quant_bits 4`.
CUDA_VISIBLE_DEVICES=0 swift export \
    --ckpt_dir 'xxx/vx-xxx/checkpoint-xxx' --merge_lora true
```

我有一个问题是这个脚本只指定了 checkpoint 的路径，即 lora 训练完的 lora 文件路径，没有base mode的路径。 请问这可以融合？？？

我现在有一个lora后的 glm3-32K 的lora 模型文件，想 merge一下，请问该如何 merge 呢？

**Comment by Jintao-Huang** [comment]
> halo。我想请教一下呀~
> 
> 说明文档中：https://github.com/modelscope/swift/blob/main/docs/source/LLM/LLM%E5%BE%AE%E8%B0%83%E6%96%87%E6%A1%A3.md#merge-lora
> 
> 给的模型 merge lora 脚本是：
> 
> ```
> # 如果你需要量化, 可以指定`--quant_bits 4`.
> CUDA_VISIBLE_DEVICES=0 swift export \
>     --ckpt_dir 'xxx/vx-xxx/checkpoint-xxx' --merge_lora true
> ```
> 
> 我有一个问题是这个脚本只指定了 checkpoint 的路径，即 lora 训练完的 lora 文件路径，没有base mode的路径。 请问这可以融合？？？
> 
> 我现在有一个lora后的 glm3-32K 的lora 模型文件，想 merge一下，请问该如何 merge 呢？

会使用训练时候的base model进行merge. 训练会保存配置到ckpt_dir中

**Comment by Jintao-Huang** [comment]
> 能不能自定义一个推理的py文件，我想按行读入我的测试集，并返回response保存到一个jsonl中，便于我之后进行评估效果

https://github.com/modelscope/swift/blob/main/docs/source/LLM/LLM%E5%BE%AE%E8%B0%83%E6%96%87%E6%A1%A3.md#%E6%8E%A8%E7%90%86
这里有单样本推理的脚本

**Comment by vivixx1** [comment]
> > 能不能自定义一个推理的py文件，我想按行读入我的测试集，并返回response保存到一个jsonl中，便于我之后进行评估效果
> 
> https://github.com/modelscope/swift/blob/main/docs/source/LLM/LLM%E5%BE%AE%E8%B0%83%E6%96%87%E6%A1%A3.md#%E6%8E%A8%E7%90%86 这里有单样本推理的脚本

可是这个我如何把model type设定为本地下载好的模型呢？设定好之后直接运行这个py文件，不需要别的sh脚本吧？

**Comment by vivixx1** [comment]
Traceback (most recent call last):
  File "myinfer.py", line 11, in <module>
    template_type = get_default_template_type(model_id_or_path)
  File "/swift/swift/llm/utils/model.py", line 2786, in get_default_template_type
    return MODEL_MAPPING[model_type].get('template')
KeyError: '/ai/123/123/'
这个单样本的我上午就试过不行的

**Comment by vivixx1** [comment]
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0,1'

from swift.llm import (
    get_model_tokenizer, get_template, inference, ModelType, get_default_template_type
)
from swift.tuners import Swift

ckpt_dir = '/ai/outfile/qwen-72b-chat-int8/v8-20240325-144934/checkpoint-159/'
model_type = '/ai/123/123/'
template_type = get_default_template_type(model_type)

model, tokenizer = get_model_tokenizer(model_type, model_kwargs={'device_map': 'auto'})

model = Swift.from_pretrained(model_type, ckpt_dir, inference_mode=True)
template = get_template(template_type, tokenizer)

这是py文件上面的部分

**Comment by vivixx1** [comment]
难道一定要把本地的模型注册成qwen_72b_chat_int8吗

**Comment by vivixx1** [comment]
我服务器会把每次缓存的模型都删除掉，没办法保存为长期存储，所以谓词都得下载模型推理也太慢了。。。。

**Comment by vivixx1** [comment]
![image](https://github.com/modelscope/swift/assets/143391981/c22d632f-a8aa-4def-b0fe-517b3904a4f6)
Traceback (most recent call last):
  File "myinfer.py", line 16, in <module>
    model = Swift.from_pretrained(model_type, ckpt_dir, inference_mode=True)
  File "/swift/swift/tuners/base.py", line 972, in from_pretrained
    return SwiftModel.from_pretrained(
  File "/swift/swift/tuners/base.py", line 368, in from_pretrained
    self = SwiftModel(model, adapters, extra_state_keys, inference_mode,
  File "/swift/swift/tuners/base.py", line 71, in __init__
    self.adapters[adapter_name] = self._prepare_model(
  File "/swift/swift/tuners/base.py", line 433, in _prepare_model
    for _, p in model.named_parameters():
AttributeError: 'str' object has no attribute 'named_parameters'
然后我直接通过下载的方式调用模型，下载完就报错了，无法进行推理
import json
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0,1'

from swift.llm import (
    get_model_tokenizer, get_template, inference, ModelType, get_default_template_type
)
from swift.tuners import Swift

ckpt_dir = '/ai/outfile/qwen-72b-chat-int8/v8-20240325-144934/checkpoint-159/'
model_type = ModelType.qwen_72b_chat_int8
template_type = get_default_template_type(model_type)

model, tokenizer = get_model_tokenizer(model_type, model_kwargs={'device_map': 'auto'})

model = Swift.from_pretrained(model_type, ckpt_dir, inference_mode=True)
template = get_template(template_type, tokenizer)

with open('/ai/123/测试集4.1仅题目.jsonl', 'r', encoding='utf-8') as f:
    data = [json.loads(item) for item in f]

query = "请你作为一名平面几何数学专家来协助我解析几何题目，首先找出题目中包含如点、线段、圆、多边形等，并且找出题目中平行，垂直，点在线上，点在多边形上等几何关系，并且都转化为构造语句"

output_data = []
for line in data:
    query = query + '题目:' + line['query']
    response = inference(model, template, query)
    print(f'response: {response}')
    output_data.append(response)

with open('/ai/outfile/qwen_72b_int8_test.jsonl', 'w', encoding='utf-8') as f:
    for line in output_data:
        f.write(json.dumps({'response': line}, ensure_ascii=False) + '\n')

**Comment by Jintao-Huang** [comment]
get_model_tokenizer可以传入model_id_or_path

**Comment by Jintao-Huang** [comment]
Swift.from_pretrained 传入model

**Comment by vivixx1** [comment]
![image](https://github.com/modelscope/swift/assets/143391981/29d70f97-e4e8-4753-9b74-a197f353de2e)
![image](https://github.com/modelscope/swift/assets/143391981/9fc93f9b-8d17-4940-b4d1-d53d32c7f722)
![image](https://github.com/modelscope/swift/assets/143391981/007feaf3-9eca-469f-bcef-1cd2cfbaae7c)

**Comment by vivixx1** [comment]
![image](https://github.com/modelscope/swift/assets/143391981/f8681903-bd94-477f-b23f-b64647ba086b)
![image](https://github.com/modelscope/swift/assets/143391981/58e874be-46f7-4a66-922d-0ad4e1ec0562)

**Comment by vivixx1** [comment]
排列组合了好几种，都认不出来这个路径下的模型，我还以为是后面没有/，改成/ai/123/123/也不行，我把model_type直接不要了，看了下get_template可以传入model，后面直接给传入model还是不太行

**Comment by vivixx1** [comment]
![image](https://github.com/modelscope/swift/assets/143391981/43a7edb1-d403-4e2f-9904-d62728c2e51b)

**Comment by vivixx1** [comment]
也不太行这样子

**Comment by vivixx1** [comment]
![image](https://github.com/modelscope/swift/assets/143391981/f9e2ccbe-553c-478a-b1fa-84f0f67260ac)
![image](https://github.com/modelscope/swift/assets/143391981/a557759e-655b-49df-ad8e-ce97b39fc42e)
一旦加入model_type就会下载

**Comment by vivixx1** [comment]
export NCCL_P2P_DISABLE=1
export NCCL_IB_DISABLE=1
export NCCL_DEBUG=info
export NCCL_SOCKET_IFNAME=eth0
nproc_per_node=6

PYTHONPATH=../../.. \
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5 \
torchrun \
    --nproc_per_node=$nproc_per_node \
    --master_port 29500 \
    /swift/examples/pytorch/llm/llm_sft.py \
    --model_type qwen-72b-chat-int8 --model_id_or_path /ai/123/123/ \
    --model_revision master \
    --sft_type lora \
    --tuner_backend swift \
    --template_type AUTO \
    --dtype AUTO \
    --output_dir /ai/outfile/ \
    --ddp_backend nccl \
    --custom_train_dataset_path /ai/123/训练集4.1_prompt.jsonl \
    --train_dataset_sample -1 \
    --num_train_epochs 3 \
    --max_length 2048 \
    --truncation_strategy delete \
    --check_dataset_strategy warning \
    --lora_rank 8 \
    --lora_alpha 32 \
    --lora_dropout_p 0.05 \
    --lora_target_modules DEFAULT \
    --gradient_checkpointing true \
    --batch_size 1 \
    --weight_decay 0.01 \
    --learning_rate 1e-4 \
    --gradient_accumulation_steps $(expr 16 / $nproc_per_node) \
    --max_grad_norm 0.5 \
    --warmup_ratio 0.03 \
    --eval_steps 50 \
    --save_total_limit 2 \
    --logging_steps 1 \
    --use_flash_attn true \
    --deepspeed default-zero2 \
    --save_only_model true \

最奇怪是我sft脚本就是这个路径，应该不可能是路径问题呀

**Comment by vivixx1** [comment]
![image](https://github.com/modelscope/swift/assets/143391981/85b6a84b-01c6-4021-a4a9-b347cd607342)
很奇怪的是，我加入了一个断言assert os.path.exists(model_id_or_path), f'Path does not exist: {model_id_or_path}'
但是按照log信息来看，还是进入了下载文件的那个判断条件，也就是说这个判断条件是成立的if model_id_or_path is not None and not os.path.exists(model_id_or_path):
[INFO:swift] Downloading the model from ModelScope Hub, model_id: qwen/Qwen-72B-Chat-Int8
[WARNING:modelscope] Using the master branch is fragile, please use it with caution!
[INFO:modelscope] Use user-specified model revision: master

**Comment by vivixx1** [comment]
![image](https://github.com/modelscope/swift/assets/143391981/718a73e8-540a-4225-ac0a-64746e035136)
这是最下面这个下载情况的代码

**Comment by vivixx1** [comment]
按函数里的第一个if来看，应该是不起作用吧，第二个if也不重要，应该是直接进第三个if的else才对吧

**Comment by zzisbeauty** [comment]
?

**Comment by zzisbeauty** [comment]
你一早上都在自言自语

**Comment by vivixx1** [comment]
> 你一早上都在自言自语

我在跟作者讨论这个问题bug出在哪里，说起来你为啥在我issue里

**Comment by zzisbeauty** [comment]
> > 你一早上都在自言自语
> 
> 我在跟作者讨论这个问题bug出在哪里，说起来你为啥在我issue里

我并没有说不不能提，我只是建议你提issue可以汇总讲清楚问题提明白就可以。你这样子一句一句发问题，我是作者我受不了。你属于调试一句，发一句问题。 只是建议，你可以不听。

**Comment by zzisbeauty** [comment]
你是在让别人给你帮助，不是在让别人替你做作业

**Comment by vivixx1** [comment]
> > > 你一早上都在自言自语
> > 
> > 
> > 我在跟作者讨论这个问题bug出在哪里，说起来你为啥在我issue里
> 
> 我并没有说不不能提，我只是建议你提issue可以汇总讲清楚问题提明白就可以。你这样子一句一句发问题，我是作者我受不了。你属于调试一句，发一句问题。 只是建议，你可以不听。

不好意思，我觉得你说的对，但这也是我的习惯，最后的问题也找到了，就是出在这个判断的地方

**Comment by zzisbeauty** [comment]
> 按函数里的第一个if来看，应该是不起作用吧，第二个if也不重要，应该是直接进第三个if的else才对吧

你觉得你这样子提问题，有人会去看你的 if 是哪个 if？

**Comment by vivixx1** [comment]
> > 按函数里的第一个if来看，应该是不起作用吧，第二个if也不重要，应该是直接进第三个if的else才对吧
> 
> 你觉得你这样子提问题，有人会去看你的 if 是哪个 if？

这是作者的代码呀，不是我自己写的

**Comment by vivixx1** [comment]
我不知道你为什么莫名其妙跳出来说我，这是我的思考过程，最终也找到了问题所在，现在可以等作者来查看最终问题所在，或者我干脆把镜像里这段swift代码的三个if直接删掉，只保留使用本地模型的部分

**Comment by zzisbeauty** [comment]
> 我不知道你为什么莫名其妙跳出来说我，这是我的思考过程，最终也找到了问题所在，现在可以等作者来查看最终问题所在，或者我干脆把镜像里这段swift代码的三个if直接删掉，只保留使用本地模型的部分

不用多想，我没有恶意。

**Comment by vivixx1** [comment]
我也知道你没有恶意，我能理解你的建议，我会部分接受这个建议

**Comment by vivixx1** [comment]
> > 我不知道你为什么莫名其妙跳出来说我，这是我的思考过程，最终也找到了问题所在，现在可以等作者来查看最终问题所在，或者我干脆把镜像里这段swift代码的三个if直接删掉，只保留使用本地模型的部分
> 
> 不用多想，我没有恶意。

只能说，你觉得你的方式好，我觉得我的方式也有优点，最终怎么样还是看作者怎么想，如果他觉得我这样很烦，他提出来。我可以讲的更简单明了一点
我也给你提个建议吧，不要把自己的情绪通过一个问号发泄出来，最终又说自己没有恶意

**Comment by zzisbeauty** [comment]
女的？

**Comment by zzisbeauty** [comment]
没必要啊兄弟，我只是建议你把问题记下来，表达清楚，也有助于别人帮你解决问题。 就是这样啊，你在干嘛啊

**Comment by vivixx1** [comment]
> 女的？

你几岁啊哥们，我不想在一个技术交流区说一些跟技术无关的话

**Comment by zzisbeauty** [comment]
是你在喋喋不休啊，我都没回了， 也表达我没恶意了。 那咋办，赔你100块？

**Comment by vivixx1** [comment]
> 是你在喋喋不休啊，我都没回了， 也表达我没恶意了。 那咋办，赔你100块？

哥们，谁在喋喋不休心理清楚哈，不多说了

**Comment by vivixx1** [comment]
作者您好，我总结一下我的问题
在使用下面代码的时候，我发现会自动下载模型而不是使用本地模型
import json
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0,1'

from swift.llm import (
    get_model_tokenizer, get_template, inference, ModelType, get_default_template_type
)
from swift.tuners import Swift

ckpt_dir = '/ai/outfile/qwen-72b-chat-int8/v8-20240325-144934/checkpoint-159/'
model_type = ModelType.qwen_72b_chat_int8
# template_type = get_default_template_type(model_type)
model_id_or_path = '/ai/123/123/'

assert os.path.exists(model_id_or_path), f'Path does not exist: {model_id_or_path}'
model, tokenizer = get_model_tokenizer(model_type, model_id_or_path, model_kwargs={'device_map': 'auto'})

model = Swift.from_pretrained(model, ckpt_dir, inference_mode=True)
template = get_template(model, tokenizer)

with open('/ai/123/测试集4.1仅题目.jsonl', 'r', encoding='utf-8') as f:
    data = [json.loads(item) for item in f]

通过查看源码，get_model_tokenizer调用了函数 safe_snapshot_download

def get_model_tokenizer(
        model_type: str,
        torch_dtype: Optional[Dtype] = None,
        model_kwargs: Optional[Dict[str, Any]] = None,
        load_model: bool = True,
        *,
        model_id_or_path: Optional[str] = None,
        **kwargs) -> Tuple[Optional[PreTrainedModel], PreTrainedTokenizerBase]:
    """
    torch_dtype: If you use None, it will retrieve the torch_dtype from the config.json file.
        However, if torch.float32 is retrieved, torch.float16 will be used.
    """
    model_dir = kwargs.pop('model_dir', None)  # compat with swift<1.7
    model_dir = safe_snapshot_download(
        model_type, model_id_or_path, model_dir=model_dir)

 通过查看safe_snapshot_download函数中的判断条件，再加上代码中对model_id_or_path的断言，判断出第三个if可能是存在某些问题，导致无法进入else中加载本地模型的功能

def safe_snapshot_download(model_type: str,
                           model_id_or_path: Optional[str] = None,
                           **kwargs) -> str:
    # Perform snapshot_download (ms or hf) based on model_type and model_id_or_path.
    model_info = MODEL_MAPPING[model_type]
    if model_id_or_path is None:
        model_dir = kwargs.pop('model_dir', None)  # compat with swift<1.7
        if model_dir is not None:
            model_id_or_path = model_dir
        else:
            model_id_or_path = model_info['model_id_or_path']

    if is_dist() and not is_local_master():
        dist.barrier()
    if model_id_or_path is not None and not os.path.exists(model_id_or_path):
        revision = model_info['revision']
        use_hf = model_info['use_hf']
        ignore_file_pattern = model_info['ignore_file_pattern']
        if use_hf:
            logger.info(
                f'Downloading the model from HuggingFace Hub, model_id: {model_id_or_path}'
            )
            from huggingface_hub import snapshot_download as hf_snapshot_download
            model_dir = hf_snapshot_download(
                model_id_or_path,
                repo_type='model',
                revision=revision,
                ignore_patterns=ignore_file_pattern)
        else:
            logger.info(
                f'Downloading the model from ModelScope Hub, model_id: {model_id_or_path}'
            )
            model_dir = snapshot_download(
                model_id_or_path,
                revision,
                ignore_file_pattern=ignore_file_pattern)
    else:
        model_dir = model_id_or_path
        logger.info(f'Loading the model using model_dir: {model_dir}')
    if is_dist() and is_local_master():
        dist.barrier()

    model_dir = os.path.expanduser(model_dir)
    assert os.path.isdir(model_dir), f'model_dir: {model_dir}'
    return model_dir

还请作者分析一下原因，谢谢

**Comment by zzisbeauty** [comment]
我Hidden了评论，你一条一条的已经评论的很多了，我的评论更会影响作者查看你的信息。 你最好把答复我的信息也hidden掉。有助于作者帮助你

**Comment by vivixx1** [comment]
> 我Hidden了评论，你一条一条的已经评论的很多了，我的评论更会影响作者查看你的信息。 你最好把答复我的信息也hidden掉。有助于作者帮助你

还有个？号hide一下

**Comment by Jintao-Huang** [comment]
> 作者您好，我总结一下我的问题 在使用下面代码的时候，我发现会自动下载模型而不是使用本地模型 ![image](https://private-user-images.githubusercontent.com/143391981/317122035-e9ded81f-4cbc-4467-877b-e5d3f6d07bf1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MTkzNzcsIm5iZiI6MTcxMTUxOTA3NywicGF0aCI6Ii8xNDMzOTE5ODEvMzE3MTIyMDM1LWU5ZGVkODFmLTRjYmMtNDQ2Ny04NzdiLWU1ZDNmNmQwN2JmMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyN1QwNTU3NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMDZiNzg5YWFiOWUzYTY0NWM3MzFkNTdmNmFkZDM5ZjM2Nzg3MjUyYmM4OTUxNjFmYzQ3ZGQxNmU2NWFlYjJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aan2KhkI7Vdq_D9OcjhghrggzsldQfXBH0VJqCbCfHk) ![image](https://private-user-images.githubusercontent.com/143391981/317122993-9b84af8b-fa9d-41a3-86bb-cd55dba504a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MTkzNzcsIm5iZiI6MTcxMTUxOTA3NywicGF0aCI6Ii8xNDMzOTE5ODEvMzE3MTIyOTkzLTliODRhZjhiLWZhOWQtNDFhMy04NmJiLWNkNTVkYmE1MDRhMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyN1QwNTU3NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNTU4MDI4NTY4NDQ4ODYyMmQ1NmQzMTNhMzMzMTllMGFlNGIxN2U2YTEwNmM3NDBkYTJhYWVlOGM2NDczYjE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KTJELaSF6d1hsrTg3D2WZ7OIo2JbsdCY42C89oln6gc) 通过查看源码，get_model_tokenizer调用了函数 safe_snapshot_download ![image](https://private-user-images.githubusercontent.com/143391981/317122092-a2321155-e7ca-4276-a2a7-75596a3ae65b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MTkzNzcsIm5iZiI6MTcxMTUxOTA3NywicGF0aCI6Ii8xNDMzOTE5ODEvMzE3MTIyMDkyLWEyMzIxMTU1LWU3Y2EtNDI3Ni1hMmE3LTc1NTk2YTNhZTY1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyN1QwNTU3NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YjVmNTZhMDZkZjIzMGI5ZjdhNWYzNzVjMTFiMzI4NTliOGZkZGE1N2MyMTEwMzU0Njk3MjBiODkxZTY2NzQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.R7DxdIX-ur2cpRlWppOmJ1bGJbzTMnZxsixUyu01a50) 通过查看safe_snapshot_download函数中的判断条件，再加上代码中对model_id_or_path的断言，判断出第三个if可能是存在某些问题，导致无法进入else中加载本地模型的功能 ![image](https://private-user-images.githubusercontent.com/143391981/317122316-738a1f88-b08b-4f9d-b792-4b9e4a624c3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MTkzNzcsIm5iZiI6MTcxMTUxOTA3NywicGF0aCI6Ii8xNDMzOTE5ODEvMzE3MTIyMzE2LTczOGExZjg4LWIwOGItNGY5ZC1iNzkyLTRiOWU0YTYyNGMzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyN1QwNTU3NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNWIyNzBjYjE2Yjg1OGNlZGRlOGIwNTk3ZmYyNjdhMjA1MmRhMjZlNGI3NjIzMzkwMzU3YjFlMDMwODMyMTdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Zbi5-mluXSLDgwTP5sVZTufiu-ootXIO0h6_2e781Eo) 还请作者分析一下原因，谢谢

get_model_tokenizer 传入 model_id_or_path=model_id_or_path

**Comment by vivixx1** [comment]
ckpt_dir = '/ai/outfile/qwen-72b-chat-int8/v8-20240325-144934/checkpoint-159/'
model_type = ModelType.qwen_72b_chat_int8
template_type = get_default_template_type(model_type)
model_id_or_path = '/ai/123/123/'


model, tokenizer = get_model_tokenizer(model_type, model_id_or_path=model_id_or_path, model_kwargs={'device_map': 'auto'})

model = Swift.from_pretrained(model, ckpt_dir, inference_mode=True)
template = get_template(template_type, tokenizer)

with open('/ai/123/测试集4.1仅题目.jsonl', 'r', encoding='utf-8') as f:
    data = [json.loads(item) for item in f]

搞定了，感谢作者大大，上面是完整源码
![image](https://github.com/modelscope/swift/assets/143391981/9ad1f5d3-ce09-4c93-9203-c4ef5e35f923)

**Comment by vivixx1** [comment]
![image](https://github.com/modelscope/swift/assets/143391981/17caec6d-fbb6-45bb-a020-ace59141c0ad)
又碰到了一个问题，我在sft的时候用的是dtype=auto，显卡是8*A800，查了一下是可以有bf16的，模型是qwen_72b_chat_int8
我查看到issue#434和#251中提到可能是参数fp16和bf16问题，我尝试在推理的时候加入了一个torch_dtype=model_torch_dtype参数，不过好像还是一直报错，不知道如何解决，望作者再看看这个问题
下面是sft脚本
export NCCL_P2P_DISABLE=1
export NCCL_IB_DISABLE=1
export NCCL_DEBUG=info
export NCCL_SOCKET_IFNAME=eth0
nproc_per_node=6

PYTHONPATH=../../.. \
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5 \
torchrun \
    --nproc_per_node=$nproc_per_node \
    --master_port 29500 \
    /swift/examples/pytorch/llm/llm_sft.py \
    --model_type qwen-72b-chat-int8 --model_id_or_path /ai/123/123/ \
    --model_revision master \
    --sft_type lora \
    --tuner_backend swift \
    --template_type AUTO \
    --dtype AUTO \
    --output_dir /ai/outfile/ \
    --ddp_backend nccl \
    --custom_train_dataset_path /ai/123/训练集4.1_prompt.jsonl \
    --train_dataset_sample -1 \
    --num_train_epochs 3 \
    --max_length 2048 \
    --truncation_strategy delete \
    --check_dataset_strategy warning \
    --lora_rank 8 \
    --lora_alpha 32 \
    --lora_dropout_p 0.05 \
    --lora_target_modules DEFAULT \
    --gradient_checkpointing true \
    --batch_size 1 \
    --weight_decay 0.01 \
    --learning_rate 1e-4 \
    --gradient_accumulation_steps $(expr 16 / $nproc_per_node) \
    --max_grad_norm 0.5 \
    --warmup_ratio 0.03 \
    --eval_steps 50 \
    --save_total_limit 2 \
    --logging_steps 1 \
    --use_flash_attn true \
    --deepspeed default-zero2 \
    --save_only_model true \

![image](https://github.com/modelscope/swift/assets/143391981/9e234996-b5a1-42fd-b758-61b5b925f2ea)

**Comment by Jintao-Huang** [comment]
微调的时候weight_decay 用0.1

**Comment by vivixx1** [comment]
weight_decay改成0.1了，通过查看训练日志，确实auto用的是fp16
![image](https://github.com/modelscope/swift/assets/143391981/f3982c83-e4dc-4ed9-9a29-80a6db14797a)
重新训练之后推理，仍然还是提示RuntimeError: probability tensor contains either inf, nan or element < 0
下面是代码和完整的日志，烦请作者再看看
ckpt_dir = '/ai/outfile/qwen-72b-chat-int8/v9-20240328-095126/checkpoint-120/'
model_type = ModelType.qwen_72b_chat_int8
template_type = get_default_template_type(model_type)
model_id_or_path = '/ai/123/123/'

model, tokenizer = get_model_tokenizer(model_type, model_id_or_path=model_id_or_path, model_kwargs={'device_map': 'auto'})

model = Swift.from_pretrained(model, ckpt_dir, inference_mode=True)
template = get_template(template_type, tokenizer)

2024-03-28 10:57:37,447 - modelscope - INFO - PyTorch version 2.2.1 Found.
2024-03-28 10:57:37,448 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer
2024-03-28 10:57:37,448 - modelscope - INFO - No valid ast index found from /root/.cache/modelscope/ast_indexer, generating ast index from prebuilt!
2024-03-28 10:57:37,500 - modelscope - INFO - Loading done! Current index file version is 1.13.1, with md5 8aac32faa2fe91ef40329139aa6c4716 and a total number of 972 components indexed
[INFO:swift] Loading the model using model_dir: /ai/123/123/
[INFO:swift] Setting torch_dtype: torch.float16
[INFO:swift] use gptq, ignore bnb arguments
/usr/local/lib/python3.8/dist-packages/transformers/quantizers/auto.py:155: UserWarning: You passed `quantization_config` or equivalent parameters to `from_pretrained` but the model you're loading already has a `quantization_config` attribute. The `quantization_config` from the model will be used.However, loading attributes (e.g. ['use_cuda_fp16', 'use_exllama', 'max_input_length', 'exllama_config', 'disable_exllama']) will be overwritten with the one you passed to `from_pretrained`. The rest will be ignored.
  warnings.warn(warning_msg)
Try importing flash-attention for faster inference...
Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm
/usr/local/lib/python3.8/dist-packages/transformers/modeling_utils.py:4193: FutureWarning: `_is_quantized_training_enabled` is going to be deprecated in transformers 4.39.0. Please use `model.hf_quantizer.is_trainable` instead
  warnings.warn(

Loading checkpoint shards:   0%|          | 0/39 [00:00<?, ?it/s]
Loading checkpoint shards:   3%|▎         | 1/39 [00:06<03:53,  6.15s/it]
Loading checkpoint shards:   5%|▌         | 2/39 [00:10<03:09,  5.11s/it]
Loading checkpoint shards:   8%|▊         | 3/39 [00:15<02:57,  4.93s/it]
Loading checkpoint shards:  10%|█         | 4/39 [00:19<02:48,  4.82s/it]
Loading checkpoint shards:  13%|█▎        | 5/39 [00:24<02:43,  4.81s/it]
Loading checkpoint shards:  15%|█▌        | 6/39 [00:29<02:40,  4.87s/it]
Loading checkpoint shards:  18%|█▊        | 7/39 [00:34<02:35,  4.86s/it]
Loading checkpoint shards:  21%|██        | 8/39 [00:39<02:28,  4.79s/it]
Loading checkpoint shards:  23%|██▎       | 9/39 [00:44<02:29,  4.99s/it]
Loading checkpoint shards:  26%|██▌       | 10/39 [00:49<02:26,  5.05s/it]
Loading checkpoint shards:  28%|██▊       | 11/39 [00:55<02:23,  5.12s/it]
Loading checkpoint shards:  31%|███       | 12/39 [01:00<02:18,  5.12s/it]
Loading checkpoint shards:  33%|███▎      | 13/39 [01:04<02:10,  5.01s/it]
Loading checkpoint shards:  36%|███▌      | 14/39 [01:09<02:05,  5.02s/it]
Loading checkpoint shards:  38%|███▊      | 15/39 [01:15<02:03,  5.13s/it]
Loading checkpoint shards:  41%|████      | 16/39 [01:20<01:56,  5.08s/it]
Loading checkpoint shards:  44%|████▎     | 17/39 [01:25<01:51,  5.08s/it]
Loading checkpoint shards:  46%|████▌     | 18/39 [01:30<01:43,  4.95s/it]
Loading checkpoint shards:  49%|████▊     | 19/39 [01:35<01:39,  4.99s/it]
Loading checkpoint shards:  51%|█████▏    | 20/39 [01:40<01:35,  5.04s/it]
Loading checkpoint shards:  54%|█████▍    | 21/39 [01:45<01:31,  5.08s/it]
Loading checkpoint shards:  56%|█████▋    | 22/39 [01:50<01:26,  5.11s/it]
Loading checkpoint shards:  59%|█████▉    | 23/39 [01:55<01:19,  4.99s/it]
Loading checkpoint shards:  62%|██████▏   | 24/39 [02:00<01:14,  4.98s/it]
Loading checkpoint shards:  64%|██████▍   | 25/39 [02:05<01:11,  5.12s/it]
Loading checkpoint shards:  67%|██████▋   | 26/39 [02:10<01:06,  5.09s/it]
Loading checkpoint shards:  69%|██████▉   | 27/39 [02:15<01:01,  5.09s/it]
Loading checkpoint shards:  72%|███████▏  | 28/39 [02:20<00:56,  5.09s/it]
Loading checkpoint shards:  74%|███████▍  | 29/39 [02:26<00:51,  5.14s/it]
Loading checkpoint shards:  77%|███████▋  | 30/39 [02:31<00:46,  5.22s/it]
Loading checkpoint shards:  79%|███████▉  | 31/39 [02:36<00:41,  5.22s/it]
Loading checkpoint shards:  82%|████████▏ | 32/39 [02:41<00:36,  5.20s/it]
Loading checkpoint shards:  85%|████████▍ | 33/39 [02:47<00:30,  5.15s/it]
Loading checkpoint shards:  87%|████████▋ | 34/39 [02:51<00:25,  5.07s/it]
Loading checkpoint shards:  90%|████████▉ | 35/39 [02:56<00:20,  5.07s/it]
Loading checkpoint shards:  92%|█████████▏| 36/39 [03:01<00:15,  5.05s/it]
Loading checkpoint shards:  95%|█████████▍| 37/39 [03:07<00:10,  5.07s/it]
Loading checkpoint shards:  97%|█████████▋| 38/39 [03:08<00:04,  4.10s/it]
Loading checkpoint shards: 100%|██████████| 39/39 [03:15<00:00,  4.75s/it]
Loading checkpoint shards: 100%|██████████| 39/39 [03:15<00:00,  5.01s/it]
[INFO:swift] model.max_model_len: 32768
Traceback (most recent call last):
  File "myinfer.py", line 60, in <module>
    response = inference(model, template, query)
  File "/swift/swift/llm/utils/utils.py", line 709, in inference
    generate_ids = model.generate(
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_qwen.py", line 1259, in generate
    return super().generate(
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/generation/utils.py", line 1592, in generate
    return self.sample(
  File "/usr/local/lib/python3.8/dist-packages/transformers/generation/utils.py", line 2734, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

**Comment by vivixx1** [comment]
{"query": "请你作为一名平面几何数学专家来协助我解析几何题目，首先找出题目中包含如点、线段、圆、多边形等，并且找出题目中平行，垂直，点在线上，点在多边形上等几何关系，并且都转化为构造语句\n下面我将给你一组构造语句以及对应几何关系的含义\n构造语句 | 几何关系\nPOINT A\t| 构造一个自由点A\nON_LINE C A B | C在直线AB上\nON_CIRCLE C A B\t| C在圆AB上\nON_PLINE D C A B | D在过C点平行于AB的直线上\nPERPENDICULAR A B C D | AB垂直CD\nON_BLINE C A B | C在AB的垂直平分线上\nMIDPOINT O A B | O是线段AB的中点\nINTERSECTION_LC E A B C D | E是直线AB和圆CD的交点\nINTERSECTION_LL E A B C D | E是直线AB和直线CD的交点\nEQANGLE F E B E B C\t| 约束∠FEB与∠EBC相等\nCIRCLE A B | 以A为圆心，B为圆上一点做一个圆\nTRIANGLE A B C | A,B,C组成了一个三角形\nR_TRIANGLE A B C | 直线AB与AC交于点A，角CAB为直角的直角三角形\nISO_TRIANGLE A B C | 等腰三角形ABC，AB=AC\nEQ_TRIANGLE A B C | AB=BC=CA,∠ABC=∠CAB=∠BCA=60°\nPARALLELOGRAM A B C D | ABCD是平行四边形\nRECTANGLE A B C D | ABCD是长方形\nSQUARE A B C D | ABCD是正方形\nS_ANGLE A B C x\t| ∠ABC的度数为x度\nANGLE_BISECTOR D C A B | 角CAB的角平分线，D为角平分线与BC交点\nLC_TANGENT A B O | AB是以O为圆心、OB为半径的圆的切线\nPARALLEL A B C D | AB∥CD\nRATIO A F C F 1 2 | AF：FC=1：2\nEQDISTANCE A B C D | AB与CD长度相等\nEQ_PRODUCT A B A B B C B D | 两条边相乘与另两条边相乘相等AB*AB = BC*BD只能用于待证结论\nCON_TRIANGLE A B C D E F | △ABC≌△DEF\nSIM_TRIANGLE A B C D E F | △ABC∽△DEF\nCOLLINEAR A B C\t| A,B,C三点共线\n注意：请严格按照我提供的构造语句解析几何题目\n题目:已知$$\\angle A=\\angle D=90^\\circ$$，$$E$$、$$F$$在线段$$BC$$上，$$DE$$与$$AF$$交于点$$O$$，且$$AB=CD$$，$$BE=CF$$。求证：$$\\triangle ABF \\cong \\triangle DCE$$.", "response": "谓词解析:HYPOTHESES: \nPOINT A B C D E F G\nS_ANGLE C D E 90\nS_ANGLE B A F 90\nON_LINE E B C\nON_LINE F B C\nINTERSECTION_LL G A F D E\nEQDISTANCE A B C D\nEQDISTANCE B E C F\nSHOW: CON_TRIANGLE A B F D C E"}
{"query": "请你作为一名平面几何数学专家来协助我解析几何题目，首先找出题目中包含如点、线段、圆、多边形等，并且找出题目中平行，垂直，点在线上，点在多边形上等几何关系，并且都转化为构造语句\n下面我将给你一组构造语句以及对应几何关系的含义\n构造语句 | 几何关系\nPOINT A\t| 构造一个自由点A\nON_LINE C A B | C在直线AB上\nON_CIRCLE C A B\t| C在圆AB上\nON_PLINE D C A B | D在过C点平行于AB的直线上\nPERPENDICULAR A B C D | AB垂直CD\nON_BLINE C A B | C在AB的垂直平分线上\nMIDPOINT O A B | O是线段AB的中点\nINTERSECTION_LC E A B C D | E是直线AB和圆CD的交点\nINTERSECTION_LL E A B C D | E是直线AB和直线CD的交点\nEQANGLE F E B E B C\t| 约束∠FEB与∠EBC相等\nCIRCLE A B | 以A为圆心，B为圆上一点做一个圆\nTRIANGLE A B C | A,B,C组成了一个三角形\nR_TRIANGLE A B C | 直线AB与AC交于点A，角CAB为直角的直角三角形\nISO_TRIANGLE A B C | 等腰三角形ABC，AB=AC\nEQ_TRIANGLE A B C | AB=BC=CA,∠ABC=∠CAB=∠BCA=60°\nPARALLELOGRAM A B C D | ABCD是平行四边形\nRECTANGLE A B C D | ABCD是长方形\nSQUARE A B C D | ABCD是正方形\nS_ANGLE A B C x\t| ∠ABC的度数为x度\nANGLE_BISECTOR D C A B | 角CAB的角平分线，D为角平分线与BC交点\nLC_TANGENT A B O | AB是以O为圆心、OB为半径的圆的切线\nPARALLEL A B C D | AB∥CD\nRATIO A F C F 1 2 | AF：FC=1：2\nEQDISTANCE A B C D | AB与CD长度相等\nEQ_PRODUCT A B A B B C B D | 两条边相乘与另两条边相乘相等AB*AB = BC*BD只能用于待证结论\nCON_TRIANGLE A B C D E F | △ABC≌△DEF\nSIM_TRIANGLE A B C D E F | △ABC∽△DEF\nCOLLINEAR A B C\t| A,B,C三点共线\n注意：请严格按照我提供的构造语句解析几何题目\n题目:在$$\\triangle ABC$$中，$$AC=BC$$，直线$$l$$经过顶点$$C$$，过$$A$$，$$B$$两点分别作$$l$$的垂线$$AE$$，$$BF$$，$$E$$，$$F$$为垂足，$$AE=CF$$．求证：$$\\angle ACB=90^\\circ$$．", "response": "谓词解析:HYPOTHESES: \nPOINT A B C D E F\nPERPENDICULAR E A C D E\nPERPENDICULAR F B C D F\nEQDISTANCE A C C B\nEQDISTANCE A E C F\nSHOW: PERPENDICULAR A C C B"}

这里有我的部分训练数据，测试数据也是类似拼接

**Comment by Jintao-Huang** [comment]
浮点数越界我也没有办法... inf了

**Comment by Jintao-Huang** [comment]
估计有些激活的值比较大，这在句子中出现低频词汇时 容易出现。你或许可以试试lora, 然后使用bf16

**Comment by xiaolvtongxue-zt** [comment]
> > halo。我想请教一下呀~
> > 说明文档中：https://github.com/modelscope/swift/blob/main/docs/source/LLM/LLM%E5%BE%AE%E8%B0%83%E6%96%87%E6%A1%A3.md#merge-lora
> > 给的模型 merge lora 脚本是：
> > ```
> > # 如果你需要量化, 可以指定`--quant_bits 4`.
> > CUDA_VISIBLE_DEVICES=0 swift export \
> >     --ckpt_dir 'xxx/vx-xxx/checkpoint-xxx' --merge_lora true
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我有一个问题是这个脚本只指定了 checkpoint 的路径，即 lora 训练完的 lora 文件路径，没有base mode的路径。 请问这可以融合？？？
> > 我现在有一个lora后的 glm3-32K 的lora 模型文件，想 merge一下，请问该如何 merge 呢？
> 
> 会使用训练时候的base model进行merge. 训练会保存配置到ckpt_dir中

你好，我想请问一下，我在训练时，使用qloar（即使用4比特量化的模型进行训练），训练后，也是用这种方式可以合并模型进行导出嘛？不需要传入其他参数了？qloar训练的模型，也能进行合并？这里面的机制是？

**Comment by vivixx1** [comment]
> 估计有些激活的值比较大，这在句子中出现低频词汇时 容易出现。你或许可以试试lora, 然后使用bf16

好的，所以我想尝试一下qwen1half-72b-chat模型，想把下载下来的模型保存到外部存储，通过查询应该是要修改函数snapshot_download，但是把这个经过修改的model.py复制到/swift/swift/llm/utils/model.py路径下时，总是会出现下面两种问题，望作者解答一下如何把这个下载到外存而不是缓存，因为每次训练服务器都会自动删除缓存
Traceback (most recent call last):
  File "/swift/examples/pytorch/llm/llm_sft.py", line 2, in <module>
    import custom
  File "/swift/examples/pytorch/llm/custom.py", line 10, in <module>
    from swift.llm import (LoRATM, Template, TemplateType, dataset_map,
  File "/swift/swift/llm/__init__.py", line 5, in <module>
    from .utils import *
  File "/swift/swift/llm/utils/__init__.py", line 2, in <module>
    from .argument import (AppUIArguments, DeployArguments, DPOArguments,
  File "/swift/swift/llm/utils/argument.py", line 29, in <module>
    from .model import (MODEL_MAPPING, dtype_mapping, get_additional_saved_files,
  File "/swift/swift/llm/utils/model.py", line 2356, in <module>
    TemplateType.telechat,
AttributeError: type object 'TemplateType' has no attribute 'telechat'
Traceback (most recent call last):
  File "/swift/examples/pytorch/llm/llm_sft.py", line 2, in <module>
    import custom
  File "/swift/examples/pytorch/llm/custom.py", line 10, in <module>
    from swift.llm import (LoRATM, Template, TemplateType, dataset_map,
  File "/swift/swift/llm/__init__.py", line 5, in <module>
    from .utils import *
  File "/swift/swift/llm/utils/__init__.py", line 2, in <module>
    from .argument import (AppUIArguments, DeployArguments, DPOArguments,
  File "/swift/swift/llm/utils/argument.py", line 29, in <module>
    from .model import (MODEL_MAPPING, dtype_mapping, get_additional_saved_files,
  File "/swift/swift/llm/utils/model.py", line 2631, in <module>
    TemplateType.llava_mistral_instruct,
AttributeError: type object 'TemplateType' has no attribute 'llava_mistral_instruct'
![image](https://github.com/modelscope/swift/assets/143391981/a018dfa6-647c-4f03-bcfb-aa82d74e144d)

**Comment by vivixx1** [comment]
无论是先删除后复制，还是强制复制，或者从镜像中删除model.py，再复制进去，再push镜像到服务器，都会出现上述的问题

**Comment by vivixx1** [comment]
> weight_decay改成0.1了，通过查看训练日志，确实auto用的是fp16 ![image](https://private-user-images.githubusercontent.com/143391981/317580093-f3982c83-e4dc-4ed9-9a29-80a6db14797a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3NjI5MTksIm5iZiI6MTcxMTc2MjYxOSwicGF0aCI6Ii8xNDMzOTE5ODEvMzE3NTgwMDkzLWYzOTgyYzgzLWU0ZGMtNGVkOS05YTI5LTgwYTZkYjE0Nzk3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMFQwMTM2NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZDE3MjlmMTIzMDY1ZmZiNDk0NzU0MGI0YmFhY2ZkM2I5MDEyZjQyNWE1MjZlNDBkYWQ1ODVkNTYxNTA0YmIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G1ARcgrs4oisYDJdY0_59FuXvKgRtHIZfFAEHmhiwlY) 重新训练之后推理，仍然还是提示RuntimeError: probability tensor contains either inf, nan or element < 0 下面是代码和完整的日志，烦请作者再看看 ckpt_dir = '/ai/outfile/qwen-72b-chat-int8/v9-20240328-095126/checkpoint-120/' model_type = ModelType.qwen_72b_chat_int8 template_type = get_default_template_type(model_type) model_id_or_path = '/ai/123/123/'
> 
> model, tokenizer = get_model_tokenizer(model_type, model_id_or_path=model_id_or_path, model_kwargs={'device_map': 'auto'})
> 
> model = Swift.from_pretrained(model, ckpt_dir, inference_mode=True) template = get_template(template_type, tokenizer)
> 
> query = """请你作为一名平面几何数学专家来协助我解析几何题目，首先找出题目中包含如点、线段、圆、多边形等，并且找出题目中平行，垂直，点在线上，点在多边形上等几何关系，并且都转化为构造语句"""
> 
> output_data = [] for line in data: query = query + '题目:' + line['query'] response = inference(model, template, query) print(f'response: {response}') output_data.append(response)
> 
> with open('/ai/outfile/qwen_72b_int8_test.jsonl', 'w', encoding='utf-8') as f: for line in output_data: f.write(json.dumps({'response': line}, ensure_ascii=False) + '\n')
> 
> 2024-03-28 10:57:37,447 - modelscope - INFO - PyTorch version 2.2.1 Found. 2024-03-28 10:57:37,448 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer 2024-03-28 10:57:37,448 - modelscope - INFO - No valid ast index found from /root/.cache/modelscope/ast_indexer, generating ast index from prebuilt! 2024-03-28 10:57:37,500 - modelscope - INFO - Loading done! Current index file version is 1.13.1, with md5 8aac32faa2fe91ef40329139aa6c4716 and a total number of 972 components indexed [INFO:swift] Loading the model using model_dir: /ai/123/123/ [INFO:swift] Setting torch_dtype: torch.float16 [INFO:swift] use gptq, ignore bnb arguments /usr/local/lib/python3.8/dist-packages/transformers/quantizers/auto.py:155: UserWarning: You passed `quantization_config` or equivalent parameters to `from_pretrained` but the model you're loading already has a `quantization_config` attribute. The `quantization_config` from the model will be used.However, loading attributes (e.g. ['use_cuda_fp16', 'use_exllama', 'max_input_length', 'exllama_config', 'disable_exllama']) will be overwritten with the one you passed to `from_pretrained`. The rest will be ignored. warnings.warn(warning_msg) Try importing flash-attention for faster inference... Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm /usr/local/lib/python3.8/dist-packages/transformers/modeling_utils.py:4193: FutureWarning: `_is_quantized_training_enabled` is going to be deprecated in transformers 4.39.0. Please use `model.hf_quantizer.is_trainable` instead warnings.warn(
> 
> Loading checkpoint shards: 0%| | 0/39 [00:00<?, ?it/s] Loading checkpoint shards: 3%|▎ | 1/39 [00:06<03:53, 6.15s/it] Loading checkpoint shards: 5%|▌ | 2/39 [00:10<03:09, 5.11s/it] Loading checkpoint shards: 8%|▊ | 3/39 [00:15<02:57, 4.93s/it] Loading checkpoint shards: 10%|█ | 4/39 [00:19<02:48, 4.82s/it] Loading checkpoint shards: 13%|█▎ | 5/39 [00:24<02:43, 4.81s/it] Loading checkpoint shards: 15%|█▌ | 6/39 [00:29<02:40, 4.87s/it] Loading checkpoint shards: 18%|█▊ | 7/39 [00:34<02:35, 4.86s/it] Loading checkpoint shards: 21%|██ | 8/39 [00:39<02:28, 4.79s/it] Loading checkpoint shards: 23%|██▎ | 9/39 [00:44<02:29, 4.99s/it] Loading checkpoint shards: 26%|██▌ | 10/39 [00:49<02:26, 5.05s/it] Loading checkpoint shards: 28%|██▊ | 11/39 [00:55<02:23, 5.12s/it] Loading checkpoint shards: 31%|███ | 12/39 [01:00<02:18, 5.12s/it] Loading checkpoint shards: 33%|███▎ | 13/39 [01:04<02:10, 5.01s/it] Loading checkpoint shards: 36%|███▌ | 14/39 [01:09<02:05, 5.02s/it] Loading checkpoint shards: 38%|███▊ | 15/39 [01:15<02:03, 5.13s/it] Loading checkpoint shards: 41%|████ | 16/39 [01:20<01:56, 5.08s/it] Loading checkpoint shards: 44%|████▎ | 17/39 [01:25<01:51, 5.08s/it] Loading checkpoint shards: 46%|████▌ | 18/39 [01:30<01:43, 4.95s/it] Loading checkpoint shards: 49%|████▊ | 19/39 [01:35<01:39, 4.99s/it] Loading checkpoint shards: 51%|█████▏ | 20/39 [01:40<01:35, 5.04s/it] Loading checkpoint shards: 54%|█████▍ | 21/39 [01:45<01:31, 5.08s/it] Loading checkpoint shards: 56%|█████▋ | 22/39 [01:50<01:26, 5.11s/it] Loading checkpoint shards: 59%|█████▉ | 23/39 [01:55<01:19, 4.99s/it] Loading checkpoint shards: 62%|██████▏ | 24/39 [02:00<01:14, 4.98s/it] Loading checkpoint shards: 64%|██████▍ | 25/39 [02:05<01:11, 5.12s/it] Loading checkpoint shards: 67%|██████▋ | 26/39 [02:10<01:06, 5.09s/it] Loading checkpoint shards: 69%|██████▉ | 27/39 [02:15<01:01, 5.09s/it] Loading checkpoint shards: 72%|███████▏ | 28/39 [02:20<00:56, 5.09s/it] Loading checkpoint shards: 74%|███████▍ | 29/39 [02:26<00:51, 5.14s/it] Loading checkpoint shards: 77%|███████▋ | 30/39 [02:31<00:46, 5.22s/it] Loading checkpoint shards: 79%|███████▉ | 31/39 [02:36<00:41, 5.22s/it] Loading checkpoint shards: 82%|████████▏ | 32/39 [02:41<00:36, 5.20s/it] Loading checkpoint shards: 85%|████████▍ | 33/39 [02:47<00:30, 5.15s/it] Loading checkpoint shards: 87%|████████▋ | 34/39 [02:51<00:25, 5.07s/it] Loading checkpoint shards: 90%|████████▉ | 35/39 [02:56<00:20, 5.07s/it] Loading checkpoint shards: 92%|█████████▏| 36/39 [03:01<00:15, 5.05s/it] Loading checkpoint shards: 95%|█████████▍| 37/39 [03:07<00:10, 5.07s/it] Loading checkpoint shards: 97%|█████████▋| 38/39 [03:08<00:04, 4.10s/it] Loading checkpoint shards: 100%|██████████| 39/39 [03:15<00:00, 4.75s/it] Loading checkpoint shards: 100%|██████████| 39/39 [03:15<00:00, 5.01s/it] [INFO:swift] model.max_model_len: 32768 Traceback (most recent call last): File "myinfer.py", line 60, in response = inference(model, template, query) File "/swift/swift/llm/utils/utils.py", line 709, in inference generate_ids = model.generate( File "/root/.cache/huggingface/modules/transformers_modules/modeling_qwen.py", line 1259, in generate return super().generate( File "/usr/local/lib/python3.8/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "/usr/local/lib/python3.8/dist-packages/transformers/generation/utils.py", line 1592, in generate return self.sample( File "/usr/local/lib/python3.8/dist-packages/transformers/generation/utils.py", line 2734, in sample next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1) RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

![image](https://github.com/modelscope/swift/assets/143391981/734fe659-592e-4643-8d17-1c395f6c4f99)
https://github.com/THUDM/ChatGLM-6B/issues/31
从这个帖子里看到一个回答很牛逼，加入了对inf和<0值的处理函数，把inf值换为能处理的最大值，<0的值换为0，但是看到transformer里的说法，一定程度上会降低生成速度

 :class:`~transformers.LogitsProcessor` that removes all :obj:`nan` and :obj:`inf` values to avoid the generation method to fail. Note that using the logits processor should only be used if necessary since it can slow down the generation method. :obj:`max_length` is reached.

**Comment by Jintao-Huang** [comment]
> 外部存储

这个是需要同时指定 model_type和model_id_or_path 可以查看命令行参数的文档

**Comment by vivixx1** [comment]
> > 外部存储
> 
> 这个是需要同时指定 model_type和model_id_or_path 可以查看命令行参数的文档

可能我上面没说清楚，我是想下载到外部存储，不是从外部存储读取，不过没事了，我直接从huggingface下载，从外部存储读取了

**Comment by vivixx1** [comment]
os.environ['CUDA_VISIBLE_DEVICES'] = '0,1'

from swift.llm import (
    get_model_tokenizer, get_template, inference, ModelType, get_default_template_type
)
from swift.tuners import Swift

ckpt_dir = '/ai/outfile/qwen1half-72b-chat/v2-20240330-103233/checkpoint-150/'
model_type = ModelType.qwen1half_72b_chat
template_type = get_default_template_type(model_type)
model_id_or_path = '/ai/qwenhalf72bchat/Qwen1.5-72B-Chat/'

model, tokenizer = get_model_tokenizer(model_type, model_id_or_path=model_id_or_path, model_kwargs={'device_map': 'auto'})

model = Swift.from_pretrained(model, ckpt_dir, inference_mode=True)

# debug_overflow = DebugUnderflowOverflow(model)
template = get_template(template_type, tokenizer)

model.generation_config = GenerationConfig(
            max_new_tokens=2048,
            temperature=0.9,
            repetition_penalt=1.05,
            do_sample=True
)


这是最终推理的脚本供大家参考

**Comment by vivixx1** [comment]
#模型下载
from modelscope import snapshot_download
model_dir = snapshot_download('qwen/Qwen1.5-72B-Chat', cache_dir='/ai/新建文件夹')

补充一个下载脚本，直接通过这个脚本下载到本地cache_dir路径，然后在微调或者推理的时候指定这个路径即可
